### ISSUE TITLE
Generate only one module at a time

### ISSUE THREAD

**Issue by ronniedroid** [salman-abedin/uniblocks#2]
Hello

I see on the demostration gif you are generating only the vol module with `uniblocks --gen vol`

I am also to use the syntax `uniblocks --gen <tag>` but it is printing the who bar regardless of what tag I specify. 

Best
Ronnie Nissan

**Comment by salman-abedin** [comment]
yeah I only wrote that flag for demonstration purpose.  
Uniblocks unifies all the modules so I figured there is no need for generating individual modules.
